apiVersion: v1
kind: Service
metadata:
  name: book-library-ui-svc
  namespace: test-argocd-dev
  labels: 
    application: test-argocd
spec:
  selector: 
    app: book-library-ui-service
  
  ports:
    - name: http
      port: 80
      targetPort: 80
    
  
