
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-library-ui-deployments
  namespace: test-argocd-dev
  labels: 
    application: test-argocd  
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: book-library-ui-service
      namespace: test-argocd-dev
  template:
    metadata:
      labels: 
        app: book-library-ui-service
        namespace: test-argocd-dev
    spec:
      serviceAccountName: bozobooks-app
      containers:
        - name: book-library-ui-service
          image: abvijaykumar/test-argocd-ui-service:64
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BOOK_LIB_SERVICE_URL
              value: http://book-library-service-svc.test-argocd-dev.svc.cluster.local:8080
            - name: REACT_APP_BOOK_INFO_SERVICE_URL
              value: http://book-info-service-svc.test-argocd-dev.svc.cluster.local:8080
