apiVersion: v1
kind: Service
metadata:
  name: book-library-postgres-db-svc
  namespace: test-argocd-dev
  labels:
    app: book-library-postgres-db-svc
    application: test-argocd
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: book-library-postgres-db