apiVersion: v1
kind: Service
metadata:
  name: book-library-service-svc
  namespace: test-argocd-dev
  labels: 
    application: test-argocd
spec:
  selector: 
    app: book-library-service
  
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    
  
