apiVersion: v1
kind: Service
metadata:
  name: redis-cache-service
  namespace: test-argocd-dev
  labels: 
    application: test-argocd  
spec:
  selector:
    app: redis-cache-service
    namespace: test-argocd-dev
  ports:
    - port: 6379
      targetPort: 6479