apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache-deployments
  namespace: test-argocd-dev
  labels: 
    application: test-argocd  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache-service
      namespace: test-argocd-dev
  template:
    metadata:
      labels:
        app: redis-cache-service
        namespace: test-argocd-dev
    spec:
      serviceAccountName: bozobooks-app
      containers:
        - name: redis-cache-service
          image: redis
