apiVersion: v1
kind: ServiceAccount
metadata:
  name: bozobooks-app
  namespace: test-argocd-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bozo-book-cluster-role
  namespace: test-argocd-dev
# Grant access to configmaps for external configuration
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bozo-book-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: bozo-book-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: bozobooks-app
    namespace: test-argocd-dev